<?xml version="1.0" encoding="utf-8"?>
<Database Name="cspad" Class="ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=server;Initial Catalog=cspad;Persist Security Info=True;User ID=jgimness" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="cspadConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pastes" Member="Pastes">
    <Type Name="Paste">
      <Column Name="PasteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccess" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompressedText" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="CreatorIp" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
    </Type>
  </Table>
</Database>